server:
  port: 9090

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wjl1234
mybatis:
  type-aliases-package: com.example.demo.bean
  mapper-locations: classpath:mapper/*Mapper.xml
#showSql
logging:
  level:
    com:
      example:
        mapper : debug
